### PR TITLE
new statistic: span length collector

### PR DESCRIPTION
**Pull request by ArneBinder**
Collect the lengths of span annotations. 

Either in means of characters:
```
python src/evaluate_documents.py dataset=argmicro_prepared metric=span_lengths_characters
```
or in means of tokens (this will internally tokenize the text documents):
```
python src/evaluate_documents.py dataset=argmicro_prepared metric=span_lengths_tokens metric.tokenized_document_type=src.document.types.TokenDocumentWithLabeledEntitiesAndRelations
```

If a list of `labels` is provided, collect result per label (note that the list of labels need to cover all labels that are in the respective annotation layer of the dataset):
```
python src/evaluate_documents.py dataset=argmicro_prepared metric=span_lengths_characters +metric.labels=[opp,pro]
``` 

The latter is especially useful to determine what max input length is required for the transformer models.

Also see the respective configs, `metric/span_lengths_characters` and `metric/span_lengths_tokens`, for further information.

NOTE: This requires https://github.com/ChristophAlt/pytorch-ie/pull/315.

### CODE REVIEW

**Comment by ArneBinder** [comment]
@idalr please have a look at this

**Comment by idalr** [comment]
Hi @ArneBinder 

I tried running these on all datasets, and the first and third commands ran fine. However, I encountered the following errors in the following datasets with the second command:
1. in aae2 
```
ValueError: cannot find token span for character span: "
", text="....."
```
2. in abstract, cdcp, sciarg
```
KeyError: "Document has no attribute 'partitions'."'
```
3. in scidtb *(only with validation set)*
```
ZeroDivisionError: division by zero
```

I also ran into errors 1. and 2. in some datasets when running the `metric=count_relation_argument_token_distances metric.tokenized_document_type=src.document.types.TokenDocumentWithLabeledEntitiesAndRelations` in #102. But I'm not sure where to look for the source of these errors. 

Any hints?

**Comment by ArneBinder** [comment]
Hi @idalr,

> `ValueError: cannot find token span for character span: " ", text="....."`

 I can not reproduce this. Please provide a full command.

> `KeyError: "Document has no attribute 'partitions'."'`

That means, that the documents in your dataset have `partitions`, but the result document don't have them. All all annotation layers that are in the input documents need to be covered in the result document type. You need to use another `tokenized_document_type`. See [here](https://github.com/ArneBinder/pie-document-level/blob/main/src/document/types.py) for options that are already implemented.

Jatin also mentioned that this is not intuitive, maybe I will relax this constraint, if possible. Thanks for reporting!

> `ZeroDivisionError: division by zero`

I also can not reproduce this one.

**Comment by idalr** [comment]
fyi @ArneBinder 

for `ValueError`, the full command was 
```
python src/evaluate_documents.py dataset=aae2_prepared metric=count_relation_argument_token_distances metric.tokenized_document_type=src.document.types.TokenDocumentWithLabeledEntitiesAndRelations
```
The whole error msg was very long, and I saved it as `.txt` file here:
[value-error_aae2.txt](https://github.com/ArneBinder/pie-document-level/files/12396908/value-error_aae2.txt)


In the `ZeroDivisionError` it was
```
python src/evaluate_documents.py dataset=scidtb_argmin_prepared metric=span_lengths_characters +metric.labels=[proposal,assertion,result,observation,means,description]
```

and thanks for the guide on `partition`, seems to work at least with `cdcp` now!

**Comment by ArneBinder** [comment]
@idalr

> for `ValueError`, the full command was

ok, I see. The problem here is, that if we tokenize the document and try to re-align the character-spans with the tokens, it can happen that we can not find a token-span for a certain character-span because the span starts or ends outside of any token (maybe there is much whitespace in the text and the annotation was not done very well). To still be able to convert such documents, I added the parameter `strict_span_conversion` to the method `tokenizer_document` which is used in `SpanLengthCollector` and `TokenCountCollector` internally to tokenize the text and realign all annotations (see [here](https://github.com/ChristophAlt/pytorch-ie/pull/315) for the respective PR). I already added this to the `span_length_tokens` config (see [here](https://github.com/ArneBinder/pie-document-level/blob/main/configs/metric/span_lengths_tokens.yaml#L10)), but forgot to set it for the `count_relation_argument_token_distances` config. You can set it via the command line for now. This will skip all spans (and dependent annotations such as relations) if teh cyn not be converted. However, I real solution would be to fix the span annotations to start / end not at whitespace with some automatic conversion. I will look into that when I find some time.

> In the `ZeroDivisionError` it was

Ok, this is a bug in `DocumentStatistic` of pytorch-ie that occurs when there are no scores / values to aggregate. I will fix this soon and let you know.

**Comment by ArneBinder** [comment]
> In the `ZeroDivisionError` it was

This is fixed, see [here](https://github.com/ChristophAlt/pytorch-ie/pull/316). Please re-install PyTorch-IE.

I also just implemented #114, please have a look and pull the recent changes.

**Comment by ArneBinder** [comment]
> for `ValueError`, the full command was

This should be mostly fixed with #115. Please update as soon as this is merged. However, for `sciarg` it will be still necessary to set `+metric.tokenize_kwargs.strict_span_conversion=false` on the command line because the issues there can not be fixed by trimming the spans.

**Comment by idalr** [comment]
Thank you! I tried running and no longer encountered the previous errors here.

**Pull request merged**
